<a href="https://colab.research.google.com/github/Nataliya2401/DS_11/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### *1.Вектор з першими 10-ма натуральними числами та виведіть його значення.*

In [2]:
import numpy as np

In [4]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### *2.Матриця розміром 3x3, заповнена нулями*

In [5]:
m = np.zeros((3, 3), dtype=int)
print(m)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


### *3.Масив 5x5 з випадковими цілими числами в діапазоні від 1 до 10.*

In [8]:
a = np.random.randint(1,11, (5, 5))
print(a)

[[7 3 3 5 8]
 [1 3 6 7 7]
 [4 8 7 1 2]
 [3 3 1 8 5]
 [3 6 7 8 2]]


### *4.Масив 4x4, з випадковими дійсними числами в діапазоні від 0 до 1*

In [9]:
m = np.random.random((4, 4))
print(m)

[[0.56122774 0.02102956 0.14359698 0.00435616]
 [0.66054012 0.92664629 0.45808265 0.50719652]
 [0.99123684 0.06331479 0.7297887  0.55570338]
 [0.23969925 0.56934945 0.68149823 0.36536545]]


### 5.два масиви (5) з випадковими цілими числами (1-10) з поелементними операціями +, -, *

In [15]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)
print(a)
print(b)
print('a+b: ', a + b)
print('a-b: ', a - b)
print('a*b: ', a * b)

[3 6 9 6 9]
[5 9 4 3 3]
a+b:  [ 8 15 13  9 12]
a-b:  [-2 -3  5  3  6]
a*b:  [15 54 36 18 27]


### *6. два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток*

In [23]:
v1 = np.random.randint(-100, 100, 7)
v2 = np.random.randint(-100, 100, 7)
print(v1)
print(v2)
print('scalar_product', np.dot(v1, v2))

[ 20  87  91  40  63 -22   0]
[  7 -56  -8   9  98  32 -10]
scalar_product 370


### *7. дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою*

In [25]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,3))
print(m1)
print(m2)
print('product: ')
print(np.dot(m1, m2))

[[8 8]
 [3 8]]
[[ 3  4  8]
 [10  4  4]]
product: 
[[104  64  96]
 [ 89  44  56]]


### *8. матриця розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю*

In [35]:
m3 = np.random.randint(1, 11, (3,3))
m3_inv = np.linalg.inv(m3)
print(m3)
print('-------------m3_inv:-----------')
print(m3_inv)
print('')
print(np.dot(m3, m3_inv))

[[5 1 2]
 [5 2 2]
 [1 2 3]]
-------------m3_inv:-----------
[[ 0.15384615  0.07692308 -0.15384615]
 [-1.          1.          0.        ]
 [ 0.61538462 -0.69230769  0.38461538]]

[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 2.22044605e-16  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]


### 9. Матриця розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [34]:
m4 = np.random.random((4,4))
print(m4)
print('--------------------------------------------')
print(m4.T)

[[0.45794623 0.14300928 0.07806612 0.22092568]
 [0.44813445 0.16695567 0.51001063 0.95890867]
 [0.3664657  0.81993262 0.11129426 0.06526805]
 [0.16239967 0.60197638 0.26508304 0.56184485]]
--------------------------------------------
[[0.45794623 0.44813445 0.3664657  0.16239967]
 [0.14300928 0.16695567 0.81993262 0.60197638]
 [0.07806612 0.51001063 0.11129426 0.26508304]
 [0.22092568 0.95890867 0.06526805 0.56184485]]


### *10.Матриця розміром 3x4 та вектор розміром 4 з випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.*



In [47]:
m5 = np.random.randint(1, 11, (3,4))
v = np.random.randint(1, 11, 4)
print(m5,'\n')
print(v, '\n')
print(np.dot(m5,v))

[[7 4 3 2]
 [3 6 4 8]
 [3 4 5 3]] 

[1 4 6 7] 

[ 55 107  70]


### *11. матриця розміром 2x3 та вектор розміром 3 з випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.*

In [48]:
m6 = np.random.randint(1, 11, (2,3))
v = np.random.randint(1, 11, 3)
print(m6,'\n')
print(v, '\n')
print(np.dot(m6,v))

[[ 3  6  1]
 [10  4  7]] 

[3 4 5] 

[38 81]


### *12. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.*

In [51]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,2))
m_product = m1 * m2
print(m1, "\n")
print(m2)
print('-----result-----')
print(m_product)

[[6 7]
 [5 1]] 

[[ 9 10]
 [ 3  8]]
-----result-----
[[54 70]
 [15  8]]


### *13. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.*

In [52]:
m_product = np.dot(m1, m2)
print(m1, "\n")
print(m2)
print('-----result-----')
print(m_product)

[[6 7]
 [5 1]] 

[[ 9 10]
 [ 3  8]]
-----result-----
[[ 75 116]
 [ 48  58]]


### *14. матрицю розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці*

In [55]:
M = np.random.randint(1, 101, (5,5))
sum_elements = 0
for i in range(5):
  for j in range(5):
    sum_elements += M[i][j]
print(M)
print('sum:  ', sum_elements)

[[58 41 22 19 94]
 [51 33 25 74 41]
 [34 55 10 69  8]
 [ 9 80  3 47 74]
 [57 16 92 65 66]]
sum:   1143
