<a href="https://colab.research.google.com/github/Nataliya2401/DS_11/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### *1.Вектор з першими 10-ма натуральними числами та виведіть його значення.*

In [2]:
import numpy as np

In [ ]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### *2.Матриця розміром 3x3, заповнена нулями*

In [ ]:
m = np.zeros((3, 3), dtype=int)
print(m)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


### *3.Масив 5x5 з випадковими цілими числами в діапазоні від 1 до 10.*

In [ ]:
a = np.random.randint(1,11, (5, 5))
print(a)

[[7 3 3 5 8]
 [1 3 6 7 7]
 [4 8 7 1 2]
 [3 3 1 8 5]
 [3 6 7 8 2]]


### *4.Масив 4x4, з випадковими дійсними числами в діапазоні від 0 до 1*

In [ ]:
m = np.random.random((4, 4))
print(m)

[[0.56122774 0.02102956 0.14359698 0.00435616]
 [0.66054012 0.92664629 0.45808265 0.50719652]
 [0.99123684 0.06331479 0.7297887  0.55570338]
 [0.23969925 0.56934945 0.68149823 0.36536545]]


### 5.два масиви (5) з випадковими цілими числами (1-10) з поелементними операціями +, -, *

In [ ]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)
print(a)
print(b)
print('a+b: ', a + b)
print('a-b: ', a - b)
print('a*b: ', a * b)

[3 6 9 6 9]
[5 9 4 3 3]
a+b:  [ 8 15 13  9 12]
a-b:  [-2 -3  5  3  6]
a*b:  [15 54 36 18 27]


### *6. два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток*

In [ ]:
v1 = np.random.randint(-100, 100, 7)
v2 = np.random.randint(-100, 100, 7)
print(v1)
print(v2)
print('scalar_product', np.dot(v1, v2))

[ 20  87  91  40  63 -22   0]
[  7 -56  -8   9  98  32 -10]
scalar_product 370


### *7. дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою*

In [ ]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,3))
print(m1)
print(m2)
print('product: ')
print(np.dot(m1, m2))

[[8 8]
 [3 8]]
[[ 3  4  8]
 [10  4  4]]
product: 
[[104  64  96]
 [ 89  44  56]]


### *8. матриця розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю*

In [ ]:
m3 = np.random.randint(1, 11, (3,3))
m3_inv = np.linalg.inv(m3)
print(m3)
print('-------------m3_inv:-----------')
print(m3_inv)
print('')
print(np.dot(m3, m3_inv))

[[5 1 2]
 [5 2 2]
 [1 2 3]]
-------------m3_inv:-----------
[[ 0.15384615  0.07692308 -0.15384615]
 [-1.          1.          0.        ]
 [ 0.61538462 -0.69230769  0.38461538]]

[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 2.22044605e-16  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]


### 9. Матриця розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [ ]:
m4 = np.random.random((4,4))
print(m4)
print('--------------------------------------------')
print(m4.T)

[[0.45794623 0.14300928 0.07806612 0.22092568]
 [0.44813445 0.16695567 0.51001063 0.95890867]
 [0.3664657  0.81993262 0.11129426 0.06526805]
 [0.16239967 0.60197638 0.26508304 0.56184485]]
--------------------------------------------
[[0.45794623 0.44813445 0.3664657  0.16239967]
 [0.14300928 0.16695567 0.81993262 0.60197638]
 [0.07806612 0.51001063 0.11129426 0.26508304]
 [0.22092568 0.95890867 0.06526805 0.56184485]]


### *10.Матриця розміром 3x4 та вектор розміром 4 з випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.*



In [ ]:
m5 = np.random.randint(1, 11, (3,4))
v = np.random.randint(1, 11, 4)
print(m5,'\n')
print(v, '\n')
print(np.dot(m5,v))

[[7 4 3 2]
 [3 6 4 8]
 [3 4 5 3]] 

[1 4 6 7] 

[ 55 107  70]


### *11. матриця розміром 2x3 та вектор розміром 3 з випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.*

In [ ]:
m6 = np.random.randint(1, 11, (2,3))
v = np.random.randint(1, 11, 3)
print(m6,'\n')
print(v, '\n')
print(np.dot(m6,v))

[[ 3  6  1]
 [10  4  7]] 

[3 4 5] 

[38 81]


### *12. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.*

In [ ]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,2))
m_product = m1 * m2
print(m1, "\n")
print(m2)
print('-----result-----')
print(m_product)

[[6 7]
 [5 1]] 

[[ 9 10]
 [ 3  8]]
-----result-----
[[54 70]
 [15  8]]


### *13. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.*

In [ ]:
m_product = np.dot(m1, m2)
print(m1, "\n")
print(m2)
print('-----result-----')
print(m_product)

[[6 7]
 [5 1]] 

[[ 9 10]
 [ 3  8]]
-----result-----
[[ 75 116]
 [ 48  58]]


### *14. матрицю розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці*

In [ ]:
M = np.random.randint(1, 101, (5,5))
sum_elements = 0
for i in range(5):
  for j in range(5):
    sum_elements += M[i][j]
print(M)
print('sum:  ', sum_elements)

[[58 41 22 19 94]
 [51 33 25 74 41]
 [34 55 10 69  8]
 [ 9 80  3 47 74]
 [57 16 92 65 66]]
sum:   1143


### *15. дві матриці 4x4, з випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.*

In [4]:
M1 = np.random.randint(1, 11, (4, 4))
M2 = np.random.randint(1, 11, (4, 4))
print(M1, '\n', '\n', M2, '\n')
print(M2 - M1)

[[2 6 8 1]
 [9 8 3 2]
 [9 3 4 4]
 [6 3 2 1]] 
 
 [[5 2 7 6]
 [5 4 1 6]
 [7 5 8 9]
 [3 4 3 3]] 

[[ 3 -4 -1  5]
 [-4 -4 -2  4]
 [-2  2  4  5]
 [-3  1  1  2]]


### *16. матрицю  3x3, з випадковими дійсними числами від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.*

In [30]:
M3 = np.random.random((3, 3))
print(M3, '\n')
n = np.zeros(3)
for i in range(3):
  n[i] = np.sum(M3[i])
print(n)

n2 = np.sum(M3, axis=1)
print(n2)

[[0.99992061 0.27649349 0.8620126 ]
 [0.12324079 0.43707688 0.09815193]
 [0.04789205 0.01728615 0.73111853]] 

[2.1384267  0.65846959 0.79629674]
[2.1384267  0.65846959 0.79629674]


### *17. матрицю 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел*

In [34]:
l = 3
n = 4
M5 = np.random.randint(-100, 100, (l, n))
M6 = np.zeros((l, n))
print (M5, '\n')
for i in range(l):
  for j in range(n):
    M6[i][j] = np.square(M5[i][j])
print(M6)

M7 = np.square(M5)
print(M7)

[[-15  82  77  10]
 [-86 -40  13  78]
 [-40  10   8  15]] 

[[ 225. 6724. 5929.  100.]
 [7396. 1600.  169. 6084.]
 [1600.  100.   64.  225.]]
[[ 225 6724 5929  100]
 [7396 1600  169 6084]
 [1600  100   64  225]]


### *18. вектор  4, з випадковими цілими числами від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел*

In [37]:
n3 = np.random.randint(1, 51, 4)
print(n3, '\n')
n4 = np.sqrt(n3)
print(n4)

[33 19 42 39] 

[5.74456265 4.35889894 6.4807407  6.244998  ]
