<a href="https://colab.research.google.com/github/Nataliya2401/DS_11/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Вектор з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

In [4]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


# 2.Матриця розміром 3x3, заповнена нулями

In [5]:
m = np.zeros((3, 3), dtype=int)
print(m)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 3.Масив 5x5 з випадковими цілими числами в діапазоні від 1 до 10.

In [8]:
a = np.random.randint(1,10, (5, 5))
print(a)

[[7 3 3 5 8]
 [1 3 6 7 7]
 [4 8 7 1 2]
 [3 3 1 8 5]
 [3 6 7 8 2]]


# Масив 4x4, з випадковими дійсними числами в діапазоні від 0 до 1

In [9]:
m = np.random.random((4, 4))
print(m)

[[0.56122774 0.02102956 0.14359698 0.00435616]
 [0.66054012 0.92664629 0.45808265 0.50719652]
 [0.99123684 0.06331479 0.7297887  0.55570338]
 [0.23969925 0.56934945 0.68149823 0.36536545]]
